Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) values (6,to_date('04-MAY-23','DD-MON-RR'),1,233.1,'VISA');
Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) values (7,to_date('04-MAY-23','DD-MON-RR'),2,194.7,'VISA');
Insert into RECEIPT (RID,RDATE,CID,TOTAL,PAYMENT_TYPE) values (8,to_date('04-MAY-23','DD-MON-RR'),4,113.4,'VISA');


Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (6,111,3);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (6,115,2);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (6,117,4);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (6,116,2);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (7,113,2);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (7,114,3);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (7,117,3);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (8,114,2);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (8,119,4);
Insert into RECEIPT_DETAILS (RID,PID,QUANTITY) values (7,115,3);

commit;
